list=["pink","black","green","orange"]
print(list)
list.append("blue")
print(list)
list.insert(2,"red")
print(list)
list.remove("pink")
print(list)
list.pop()
print(list)
list.copy()
print(list)
list.reverse()
print(list)
list.sort()
print(list)
print(list.index("orange"))
print(list.count("orange"))
list.clear()
print(list)
      
      
